name: CI/CD

on:
  push:
    branches:
      - 'time-zone'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      #     Build Docker image:
      - uses: actions/checkout@v4
      - name: Build and tag image
        run: |
          docker build -t megoru/giveaway-dev:latest .
      #     Login to Docker Hub:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #     Push image to Docker Hub:
      - name: Publish image
        run: docker push megoru/giveaway-dev:latest